### ISSUE TITLE
Pave the way for pip-installation under adverse conditions

### ISSUE THREAD

**Issue by ctheune** [flyingcircusio/appenv#3]
@wosc if you could dig up the issues you had w/ Debian then I'd be happy to investigate a potential generic way of getting environment-specific workarounds available.

**Comment by wosc** [comment]
The two concrete hiccups I remember were a) you have to `apt install python3-venv` to make `python3 -m venv` work (not much appenv can do about that I guess, except maybe detect the "it may look like it's working, but actually it's completely broken" case?) and b) a [pip bug](https://github.com/pypa/pip/issues/5857) in 18.0.1 that required pinning pip to 18.0 until it was fixed.

**Comment by ctheune** [comment]
I have a fix for that situation, as long as we're running as root. Should be good enough for now and I can bootstrap on Cumulus 4.1, so ...
